# Do you want health to be split across different world groups
isHealthSplit: true

# Do you want hunger levels to be split across different world groups
isHungerSplit: true

# Do you want exp split across different world groups
isExpSplit: true

# Do you want to allow this plugin to control which worlds are creative/survival
worldTypes: true

# Do you want to allow this plugin to manage game modes?
restoreGameModes: true

# Players you wish to never switch inventories (using YML lists)
ignore:
- Pluckerpluck
- randomStranger